import type { UserRole } from "@/types/api";

export interface AppPageConfig {
  key: string;
  title: string;
  description: string;
  path: string;
  icon: string;
  roles?: UserRole[];
  public?: boolean;
  navGroup?: string;
  mobile?: boolean;
  hidden?: boolean;
  allowBaseAdminPreview?: boolean;
}

export const navGroupOrder = ["Command", "Teaching", "Operations", "System"];

export const appPages: AppPageConfig[] = [
  {
    key: "dashboard",
    title: "Dashboard",
    description: "Live exam operations, staffing signals, and period-wide momentum.",
    path: "/dashboard",
    icon: "dashboard",
    roles: ["admin", "esq_head", "secretary", "dept_supervisor", "staff", "teacher"],
    navGroup: "Command",
    mobile: true,
  },
  {
    key: "schedule",
    title: "Exam Schedule",
    description: "Master timetable, room allocation, and invigilation coverage.",
    path: "/schedule",
    icon: "event_note",
    roles: ["admin", "esq_head", "secretary", "dept_supervisor", "staff", "teacher"],
    navGroup: "Command",
    mobile: true,
  },
  {
    key: "submissions",
    title: "Submissions",
    description: "Academic assessment records, review status, and message threads.",
    path: "/submissions",
    icon: "description",
    roles: ["admin", "esq_head", "secretary", "dept_supervisor", "teacher"],
    navGroup: "Command",
    mobile: true,
  },
  {
    key: "attendance",
    title: "Room Attendance",
    description: "Room occupancy, attendance summaries, and latest floor activity.",
    path: "/attendance",
    icon: "assignment_ind",
    roles: ["admin", "esq_head", "secretary", "dept_supervisor", "staff", "teacher"],
    navGroup: "Command",
    mobile: true,
  },
  {
    key: "checkins",
    title: "Check-ins",
    description: "Operational check-ins, confirmations, and room readiness workflow.",
    path: "/checkins",
    icon: "how_to_reg",
    roles: ["admin", "dept_supervisor", "staff", "teacher"],
    navGroup: "Command",
    mobile: true,
  },
  {
    key: "swaps",
    title: "Swap Requests",
    description: "Coverage changes, handoffs, and supervision swap coordination.",
    path: "/swaps",
    icon: "swap_horiz",
    roles: ["admin", "dept_supervisor", "staff", "teacher"],
    navGroup: "Command",
  },
  {
    key: "swaps-v2",
    title: "Swaps (V2)",
    description: "Temporary Stitch-based swaps preview for admin validation.",
    path: "/swaps-v2",
    icon: "swap_horiz",
    roles: ["admin"],
    navGroup: "Command",
  },
  {
    key: "myexam",
    title: "My Exam Work",
    description: "Personal assignments, submissions, and responsibilities.",
    path: "/myexam",
    icon: "assignment",
    roles: ["teacher"],
    navGroup: "Teaching",
  },
  {
    key: "sections",
    title: "Sections",
    description: "Course sections, enrollments, and assigned teaching records.",
    path: "/sections",
    icon: "menu_book",
    roles: ["admin", "esq_head", "secretary", "staff", "teacher"],
    navGroup: "Teaching",
  },
  {
    key: "student-search",
    title: "Student Search",
    description: "Public lookup for individual student exam timetables.",
    path: "/student-search",
    icon: "person_search",
    roles: ["student"],
    public: true,
    navGroup: "Teaching",
  },
  {
    key: "copy",
    title: "Copy Count",
    description: "Sheet counts, copy cost, and print workload tracking.",
    path: "/copy",
    icon: "print",
    roles: ["admin", "staff"],
    navGroup: "Operations",
  },
  {
    key: "print-queue",
    title: "Print Queue",
    description: "Print-shop batches, delivery status, and supply readiness.",
    path: "/print-queue",
    icon: "print",
    roles: ["print_shop"],
    navGroup: "Operations",
  },
  {
    key: "workflow",
    title: "Workflow",
    description: "Signature flow, approvals, and period release readiness.",
    path: "/workflow",
    icon: "approval",
    roles: ["admin", "esq_head", "secretary"],
    navGroup: "Operations",
  },
  {
    key: "workflow-v2",
    title: "Workflow (V2)",
    description: "Temporary Stitch-based workflow preview for admin validation.",
    path: "/workflow-v2",
    icon: "approval",
    roles: ["admin"],
    navGroup: "Operations",
  },
  {
    key: "coexam",
    title: "Co-Exam",
    description: "Shared-exam planning and group alignment controls.",
    path: "/coexam",
    icon: "groups",
    roles: ["admin"],
    navGroup: "Operations",
  },
  {
    key: "optimizer",
    title: "Optimizer",
    description: "Scheduling optimization, fairness checks, and assignment automation.",
    path: "/optimizer",
    icon: "query_stats",
    roles: ["admin"],
    navGroup: "Operations",
  },
  {
    key: "printreview",
    title: "Print Review",
    description: "Pre-print verification and output quality review.",
    path: "/printreview",
    icon: "fact_check",
    roles: ["admin"],
    navGroup: "Operations",
  },
  {
    key: "external",
    title: "External Exams",
    description: "Special exam sessions managed outside the standard timetable.",
    path: "/external",
    icon: "language",
    roles: ["admin"],
    navGroup: "Operations",
  },
  {
    key: "import",
    title: "Import Data",
    description: "Bulk data intake for terms, sections, and enrollment records.",
    path: "/import",
    icon: "upload_file",
    roles: ["admin"],
    navGroup: "System",
  },
  {
    key: "period",
    title: "Exam Periods",
    description: "Term management, active windows, and period switching.",
    path: "/period",
    icon: "calendar_month",
    roles: ["admin"],
    navGroup: "System",
  },
  {
    key: "settings",
    title: "Settings",
    description: "System configuration, guardrails, and support options.",
    path: "/settings",
    icon: "settings",
    roles: ["admin"],
    navGroup: "System",
    allowBaseAdminPreview: true,
  },
  {
    key: "settings-v2",
    title: "Settings (V2)",
    description: "Temporary Stitch-based settings and view-as preview for admin validation.",
    path: "/settings-v2",
    icon: "settings",
    roles: ["admin"],
    navGroup: "System",
    allowBaseAdminPreview: true,
  },
  {
    key: "users",
    title: "Users",
    description: "User access, role assignment, and account administration.",
    path: "/users",
    icon: "manage_accounts",
    roles: ["admin"],
    navGroup: "System",
  },
  {
    key: "students-v2",
    title: "Students (V2)",
    description: "Temporary Stitch-based student management preview for admin validation.",
    path: "/students-v2",
    icon: "school",
    roles: ["admin"],
    navGroup: "System",
  },
  {
    key: "rooms-v2",
    title: "Rooms (V2)",
    description: "Temporary Stitch-based room availability preview for admin validation.",
    path: "/rooms-v2",
    icon: "meeting_room",
    roles: ["admin"],
    navGroup: "System",
  },
  {
    key: "venues-v2",
    title: "Venues (V2)",
    description: "Temporary Stitch-based venue management preview for admin validation.",
    path: "/venues-v2",
    icon: "domain",
    roles: ["admin"],
    navGroup: "System",
  },
  {
    key: "users-v2",
    title: "Users (V2)",
    description: "Temporary Stitch-based user management preview for admin validation.",
    path: "/users-v2",
    icon: "manage_accounts",
    roles: ["admin"],
    navGroup: "System",
  },
  {
    key: "exammanager",
    title: "Exam Manager",
    description: "Manual ownership assignment for exam workflows.",
    path: "/exammanager",
    icon: "assignment_add",
    roles: ["admin"],
    navGroup: "System",
    hidden: true,
  },
  {
    key: "role-selection",
    title: "Role Selection",
    description: "Choose the production role before signing in.",
    path: "/role-selection",
    icon: "badge",
    public: true,
    hidden: true,
  },
  {
    key: "login",
    title: "Sign In",
    description: "Authenticate into the exam operations workspace.",
    path: "/login",
    icon: "login",
    public: true,
    hidden: true,
  },
];

export const mobilePageKeys = ["dashboard", "schedule", "submissions", "attendance", "checkins"];

export function getPageConfig(pathname: string) {
  return appPages.find((page) => page.path === pathname);
}
